// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD07GlppRlImYrAFnjBb11NS9uksH_M-cU',
    appId: '1:214829513513:android:5aee749e52fdde030f5538',
    messagingSenderId: '214829513513',
    projectId: 'flutterfirebase-8b021',
    storageBucket: 'flutterfirebase-8b021.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQKk5TEGutkeR1oYYoFvslmXUcOjr7AQE',
    appId: '1:214829513513:ios:b3253307bba104900f5538',
    messagingSenderId: '214829513513',
    projectId: 'flutterfirebase-8b021',
    storageBucket: 'flutterfirebase-8b021.appspot.com',
    iosClientId: '214829513513-7f5795251510cg58a0brjrfnvcajbs8d.apps.googleusercontent.com',
    iosBundleId: 'com.sopy.flutterfire',
  );
}
